
name: Test3

on:
  push:
    paths: ['.github/workflows/test3.yml']

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test job
    steps:
      - name: Step 1
        run: |
          echo 1
          false
          echo 2
          true
          echo 3
