
name: Test

on: [push]

jobs:
  test:
    runs-on: macos-12
    name: A job to run test in FreeBSD
    steps:
    - uses: actions/checkout@v2
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v0
      with:
        usesh: true
        sync: sshfs
        run: |
          pwd
          ls -lah
          whoami
          freebsd-version
          echo ls -lah /
          ls -lah /
          echo ls -lah /Users
          ls -lah /Users
          echo ls -lah /Users/runner
          ls -lah /Users/runner
          echo ls -lah /Users/runner/work
          ls -lah /Users/runner/work
          echo ls -lah /Users/runner/work/test2
          ls -lah /Users/runner/work/test2
          echo ls -lah /work
          ls -lah /work
