
name: Test3

on:
  push:
    paths: ['.github/workflows/test3.yml']

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test job
    steps:
      - name: Step 1
        run: |
          echo 1
          false || true
          echo 2
          true
          echo 3

  test2:
    runs-on: macos-12
    name: Test job 2
    steps:
      - name: Test in FreeBSD
        uses: vmactions/freebsd-vm@v0
        with:
          usesh: true
          run: |
            set -eo pipefail
            echo 1
            false
            echo 2
            true
            echo 3

  test3:
    runs-on: macos-12
    name: Test job 3
    steps:
      - name: Test in FreeBSD
        uses: vmactions/freebsd-vm@v0
        with:
          usesh: true
          run: |
            set -eo pipefail
            echo 1
            false || true
            echo 2
            true
            echo 3
