
name: Test

on: [push]

jobs:
  test:
    runs-on: macos-12
    name: A job to run test in FreeBSD
    steps:
#     - run: |
#         mv /usr/local/Homebrew/Library/Taps ~/work/Taps
#         cp -rfv /usr/local/Homebrew ~/work/Homebrew || true
#         mv ~/work/Taps /usr/local/Homebrew/Library/Taps
#         mkdir -p ~/work/Homebrew/Library/Taps/homebrew
#         cp -rfv /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core ~/work/Homebrew/Library/Taps/homebrew/homebrew-core || true
#     - uses: actions/checkout@v2
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v0
      with:
        usesh: true
        # sync: sshfs
#           mkdir -p /opt
#           mv /Users/runner/work/Homebrew /opt/homebrew
        run: |
          NONINTERACTIVE=1 bash -c "$(curl -fsSL https://github.com/bsdbrew/install/raw/HEAD/install.sh)"
#         run: |
#           pwd
#           ls -lah
#           whoami
#           freebsd-version
#           echo ls -lah /
#           ls -lah /
#           echo ls -lah /Users
#           ls -lah /Users
#           echo ls -lah /Users/runner
#           ls -lah /Users/runner
#           echo ls -lah /Users/runner/work
#           ls -lah /Users/runner/work
#           echo ls -lah /Users/runner/work/test2
#           ls -lah /Users/runner/work/test2
#           echo ls -lah ~/work
#           ls -lah ~/work
