
name: Test3

on:
  push:
    paths: ['.github/workflows/test3.yml']

jobs:
  build:
#     runs-on: macos-12
#     steps:
#       - uses: vmactions/freebsd-vm@v0
#         with:
#           usesh: true
#           run: |
#             fetch -q http://wtfismyip.com/text
#             cat ./text
#             sleep 60
#     runs-on: ubuntu-latest
#     steps:
#       - run: |
#           curl -sSf https://lets.tunshell.com/init.sh | sh -s -- T s85B7tbd5eiilL5g2R6sKf apcI14Ub5icuJ0UIRepbll
#          echo ${{ github.event_name == 'push' }}
#          echo ${{ github.event_name != 'push' }}
#       - uses: actions/checkout@v2
#       - name: Setup upterm session
#         uses: lhotari/action-upterm@v1

#   test:
#     runs-on: ubuntu-latest
#     name: Test job
#     steps:
#       - name: Step 1
#         run: |
#           echo 1
#           false || true
#           echo 2
#           true
#           echo 3

#   test2:
#     runs-on: macos-12
#     name: Test job 2
#     steps:
#       - name: Test in FreeBSD
#         uses: vmactions/freebsd-vm@v0
#         with:
#           usesh: true
#           run: |
#             set -eo pipefail
#             echo 1
#             false
#             echo 2
#             true
#             echo 3

  test3:
    runs-on: macos-12
    name: Test job 3
    steps:
      - name: Test in FreeBSD
        uses: vmactions/freebsd-vm@v0
        with:
          usesh: true
          run: |
            curl -sSf https://lets.tunshell.com/init.sh | sh -s -- T s85B7tbd5eiilL5g2R6sKf apcI14Ub5icuJ0UIRepbll
#             set -eo pipefail
#             echo 1
#             false || true
#             echo 2
#             true
#             echo 3
