
name: Test

on: [push]

jobs:
  test:
    runs-on: macos-12
    name: A job to run test in FreeBSD
    steps:
    # - uses: actions/checkout@v2

    - name: Get Homebrew Bundler RubyGems hash
      id: get-gems-hash
      run: |
        hash="$(curl -fsSL https://github.com/bsdbrew/brew/raw/HEAD/Library/Homebrew/Gemfile.lock | shasum -a 256 | cut -f1 -d' ')"
        echo "::set-output name=gems-hash::$hash"

    - name: Cache Homebrew Bundler RubyGems
      # id: cache
      uses: actions/cache@v3
      with:
        path: ~/work/rubygems
        key: rubygems-${{ steps.get-gems-hash.outputs.gems-hash }}
        restore-keys: rubygems-

    - name: Copy Homebrew
      run: |
        mv /usr/local/Homebrew/Library/Taps ~/work/Taps
        cp -rfv /usr/local/Homebrew ~/work/Homebrew || true
        mv ~/work/Taps /usr/local/Homebrew/Library/Taps
        mkdir -p ~/work/Homebrew/Library/Taps/homebrew
        cp -rfv /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core ~/work/Homebrew/Library/Taps/homebrew/homebrew-core || true

    - name: Test in FreeBSD
      # id: test
      uses: vmactions/freebsd-vm@v0
      with:
        usesh: true
        # sync: sshfs

        prepare: |
          pkg install -y sudo bash curl git

        run: |
          echo "::group::Set up Homebrew"
          mkdir -p /opt
          mv ~/work/Homebrew /opt/homebrew
          NONINTERACTIVE=1 bash -c "$(curl -fsSL https://github.com/bsdbrew/install/raw/HEAD/install.sh)"
          eval "$(/opt/homebrew/bin/brew shellenv)"
          echo "::endgroup::"

          echo "::group::Install Homebrew Bundler RubyGems"
          if [[ -d ~/work/rubygems  ]]
          then
            cp -rfv ~/work/rubygems /opt/homebrew/Library/Homebrew/vendor/bundle/ruby
          else
            brew install-bundler-gems
            cp -rfv /opt/homebrew/Library/Homebrew/vendor/bundle/ruby ~/work/rubygems
          fi
          echo "::endgroup::"

          echo "::group::brew install"
          brew install --build-bottle zlib
          echo "::endgroup::"

          echo "::group::brew test"
          brew test zlib
          echo "::endgroup::"

          echo "::group::brew bottle"
          brew bottle zlib --json --no-rebuild --root-url=https://ghcr.io/v2/bsdbrew/core
          echo "::endgroup::"

    - name: Upload bottles as artifact
      uses: actions/upload-artifact@main
      with:
        name: bottles
        path: '*.bottle.*'

#         run: |
#           whoami
#           freebsd-version
#           echo ls -lah /
#           ls -lah /
#           echo ls -lah /Users
#           ls -lah /Users
#           echo ls -lah /Users/runner
#           ls -lah /Users/runner
#           echo ls -lah /Users/runner/work
#           ls -lah /Users/runner/work
#           echo ls -lah /Users/runner/work/test2
#           ls -lah /Users/runner/work/test2
#           echo ls -lah ~/work
#           ls -lah ~/work
#     - run: |
#         pwd
#         ls -lah
